#!/usr/bin/env -S deno run -A

import $ from "jsr:@david/dax"
import * as esbuild from "npm:esbuild@0.25"
import { transformAsync } from "npm:@babel/core"
// @ts-expect-error - Types not important.
import babelTs from "npm:@babel/preset-typescript"
// @ts-expect-error - Types not important.
import babelSolid from "npm:babel-preset-solid@1.9.9"
import * as path from "node:path"
import * as fs from "node:fs"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

Deno.chdir(dir)

const pkg = JSON.parse(Deno.readTextFileSync(path.join(dir, "package.json")))
import { Script } from "../../script/src/index.ts"
const modelsUrl = Deno.env.get("OPENCODE_MODELS_URL") || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = Deno.env.get("MODELS_DEV_API_JSON")
  ? await Deno.readTextFile(Deno.env.get("MODELS_DEV_API_JSON")!)
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Deno.writeTextFile(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = Deno.args.includes("--single")

function denoTarget(os: string, arch: string): string {
  const archMap: Record<string, string> = { arm64: "aarch64", x64: "x86_64" }
  const osMap: Record<string, string> = {
    linux: "unknown-linux-gnu",
    darwin: "apple-darwin",
    win32: "pc-windows-msvc",
  }
  return `${archMap[arch]}-${osMap[os]}`
}

const allTargets: { os: string; arch: "arm64" | "x64" }[] = [
  { os: "linux", arch: "arm64" },
  { os: "linux", arch: "x64" },
  { os: "darwin", arch: "arm64" },
  { os: "darwin", arch: "x64" },
  { os: "win32", arch: "x64" },
]

function currentOs(): string {
  return Deno.build.os === "windows" ? "win32" : Deno.build.os
}

function currentArch(): string {
  if (Deno.build.arch === "x86_64") return "x64"
  if (Deno.build.arch === "aarch64") return "arm64"
  return Deno.build.arch
}

const targets = singleFlag
  ? allTargets.filter((item) => item.os === currentOs() && item.arch === currentArch())
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}

const monorepoRoot = path.resolve(dir, "../..")
const nodeModules = path.join(dir, "node_modules")
const opentuiRoot = path.resolve(monorepoRoot, "../opentui")
const opentuiCore = path.join(opentuiRoot, "packages/core")
const opentuiSolid = path.join(opentuiRoot, "packages/solid")

// Solid JSX transform via babel
const solidPlugin: esbuild.Plugin = {
  name: "solid-jsx",
  setup(build) {
    build.onLoad({ filter: /\.[tj]sx$/ }, async (args) => {
      const source = await Deno.readTextFile(args.path)
      const result = await transformAsync(source, {
        filename: args.path,
        presets: [
          [babelSolid, { moduleName: "@opentui/solid", generate: "universal" }],
          [babelTs],
        ],
      })
      return { contents: result?.code ?? "", loader: "js" }
    })
  },
}

// Keep JSR/NPM specifier imports unresolved so deno compile handles them.
const runtimeSpecifierPlugin: esbuild.Plugin = {
  name: "runtime-specifier-external",
  setup(build) {
    build.onResolve({ filter: /^jsr:/ }, (args) => ({
      path: args.path,
      external: true,
    }))
    build.onResolve({ filter: /^npm:/ }, (args) => ({
      path: args.path,
      external: true,
    }))
  },
}

// Path aliases from tsconfig: @/ -> src/, @tui/ -> src/cli/cmd/tui/
const pathAliasPlugin: esbuild.Plugin = {
  name: "path-aliases",
  setup(build) {
    build.onResolve({ filter: /^@\// }, (args) => ({
      path: resolveFile(path.resolve(dir, "src", args.path.slice(2))),
    }))
    build.onResolve({ filter: /^@tui\// }, (args) => ({
      path: resolveFile(path.resolve(dir, "src/cli/cmd/tui", args.path.slice(5))),
    }))
  },
}

// Workspace package resolution
const workspacePlugin: esbuild.Plugin = {
  name: "workspace-packages",
  setup(build) {
    const packages: Record<string, string> = {
      "@opencode-ai/util": path.join(monorepoRoot, "packages/util/src"),
      "@opencode-ai/sdk": path.join(monorepoRoot, "packages/sdk/js/src"),
      "@opencode-ai/plugin": path.join(monorepoRoot, "packages/plugin/src"),
      "@opencode-ai/script": path.join(monorepoRoot, "packages/script/src"),
      "@opentui/core": path.join(opentuiCore, "src"),
      "@opentui/solid": opentuiSolid,
    }
    build.onResolve({ filter: /^@opencode-ai\/|^@opentui\// }, (args) => {
      for (const [pkg, srcDir] of Object.entries(packages)) {
        if (args.path === pkg) {
          return { path: resolveFile(path.join(srcDir, "index")) }
        }
        if (args.path.startsWith(pkg + "/")) {
          const subpath = args.path.slice(pkg.length + 1)
          return { path: resolveFile(path.join(srcDir, subpath)) }
        }
      }
      return undefined
    })
  },
}

// @opentui/core native library resolution for Deno.
//
// zig.ts uses import.meta.resolve(`@opentui/core-${platform}-${arch}/package.json`)
// to find the native .dylib/.so/.dll. In the esbuild bundle, this template literal
// can't be resolved. Replace with a static path at build time.
const opentuiPlugin: esbuild.Plugin = {
  name: "opentui-native-lib",
  setup(build) {
    build.onLoad({ filter: /opentui\/packages\/core\/src\/zig\.ts$/ }, async (args) => {
      let code = await Deno.readTextFile(args.path)
      // Find the native library for the current build target
      const libExtMap: Record<string, string> = { darwin: "dylib", linux: "so", win32: "dll" }
      const libExt = libExtMap[currentTarget.os] ?? "so"
      const platformDir = path.join(
        opentuiCore, "node_modules",
        `@opentui/core-${currentTarget.os}-${currentTarget.arch}`,
      )
      const libPath = path.join(platformDir, `libopentui.${libExt}`)
      // Replace the import.meta.resolve + dirname line with a static path
      code = code.replace(
        /const pkgDir = dirname\(fileURLToPath\(import\.meta\.resolve\(`@opentui\/core-\$\{platform\}-\$\{arch\}\/package\.json`\)\)\)\nlet targetLibPath = resolve\(pkgDir, `libopentui\.\$\{libExt\}`\)/,
        `let targetLibPath = ${JSON.stringify(libPath)}`,
      )
      return { contents: code, loader: "ts" }
    })
  },
}

// Rewrite to a Deno.readFile call so deno compile doesn't analyze the WASM
// as a module import.
const wasmFiles: string[] = []
const wasmImportPlugin: esbuild.Plugin = {
  name: "wasm-import",
  setup(build) {
    build.onResolve({ filter: /\.wasm$/ }, (args) => {
      const resolved = path.resolve(nodeModules, ...args.path.split("/"))
      if (fs.existsSync(resolved)) {
        wasmFiles.push(resolved)
        return { path: resolved, namespace: "wasm-file" }
      }
      return { path: args.path, external: true }
    })
    build.onLoad({ filter: /.*/, namespace: "wasm-file" }, (args) => {
      const basename = path.basename(args.path, ".wasm") + ".bin"
      return {
        contents: `export default Deno.readFileSync(new URL("./${basename}", import.meta.url))`,
        loader: "js",
      }
    })
  },
}

function resolveFile(base: string): string {
  if (fs.existsSync(base) && fs.statSync(base).isFile()) return base
  for (const ext of [".ts", ".tsx", ".js", ".jsx"]) {
    const p = base + ext
    if (fs.existsSync(p)) return p
  }
  for (const ext of [".ts", ".tsx", ".js", ".jsx"]) {
    const p = path.join(base, `index${ext}`)
    if (fs.existsSync(p)) return p
  }
  return base
}

let currentTarget: { os: string; arch: string } = { os: "", arch: "" }
const plugins = [solidPlugin, runtimeSpecifierPlugin, pathAliasPlugin, workspacePlugin, opentuiPlugin, wasmImportPlugin]

const parserWorker = path.join(opentuiCore, "src/lib/tree-sitter/parser.worker.ts")

for (const item of targets) {
  currentTarget = { os: item.os, arch: item.arch }
  const name = [
    pkg.name,
    item.os === "win32" ? "windows" : item.os,
    item.arch,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p ${path.join(dir, `dist/${name}/bin`)}`

  const target = denoTarget(item.os, item.arch)
  const ext = item.os === "win32" ? ".exe" : ""
  const outBin = path.join(dir, `dist/${name}/bin/opencode${ext}`)

  const bundleDir = path.join(dir, "dist/.bundle")
  fs.mkdirSync(bundleDir, { recursive: true })

  const requireBanner = `import { createRequire as __createRequire } from "node:module";const require = __createRequire(import.meta.url);`

  const sharedConfig: esbuild.BuildOptions = {
    bundle: true,
    format: "esm",
    platform: "node",
    target: "esnext",
    conditions: ["browser"],
    // Prefer ESM entries over CJS/UMD to avoid unresolvable require() calls
    mainFields: ["module", "main"],
    // Also resolve from opentui's node_modules for its dependencies
    nodePaths: [path.join(opentuiRoot, "node_modules"), nodeModules],
    define: {
      "OPENCODE_VERSION": JSON.stringify(Script.version),
      "OPENCODE_CHANNEL": JSON.stringify(Script.channel),
      "OPENCODE_LIBC": JSON.stringify(item.os === "linux" ? "glibc" : ""),
      "OPENCODE_WORKER_PATH": "globalThis.OPENCODE_WORKER_PATH",
    },
    plugins,
    loader: { ".txt": "text" },
    logLevel: "warning",
    banner: { js: requireBanner },
  }

  // Bundle main entry (exclude worker.ts)
  console.log("  bundling main...")
  const workerPath = path.join(dir, "src/cli/cmd/tui/worker.ts")
  await esbuild.build({
    ...sharedConfig,
    entryPoints: [path.join(dir, "src/index.ts")],
    outfile: path.join(bundleDir, "main.js"),
    plugins: [...plugins, {
      name: "exclude-worker",
      setup(build) {
        // The worker is type-only imported from thread.ts but esbuild still bundles it.
        build.onResolve({ filter: /\/worker$/ }, (args) => {
          const resolved = resolveFile(path.resolve(path.dirname(args.importer), args.path))
          if (resolved === workerPath) {
            return { path: resolved, namespace: "worker-stub" }
          }
          return undefined
        })
        build.onLoad({ filter: /.*/, namespace: "worker-stub" }, () => {
          return { contents: "export {};", loader: "js" }
        })
      },
    }],
  })

  // Bundle worker
  console.log("  bundling worker...")
  await esbuild.build({
    ...sharedConfig,
    entryPoints: [path.join(dir, "src/cli/cmd/tui/worker.ts")],
    outfile: path.join(bundleDir, "worker.js"),
  })

  // Bundle parser worker (from @opentui/core) so it's self-contained
  console.log("  bundling parser worker...")
  await esbuild.build({
    ...sharedConfig,
    entryPoints: [parserWorker],
    outfile: path.join(bundleDir, "parser.worker.js"),
  })

  // Generate worker entry shim
  const workerShim = path.join(bundleDir, `worker-entry.ts`)
  await Deno.writeTextFile(
    workerShim,
    `await import("./worker.js");\n`,
  )

  // Generate entry shim
  const entryShim = path.join(bundleDir, `entry.ts`)
  await Deno.writeTextFile(
    entryShim,
    [
      `(globalThis as any).OPENCODE_VERSION = '${Script.version}';`,
      `(globalThis as any).OTUI_TREE_SITTER_WORKER_PATH = new URL("./parser.worker.js", import.meta.url).pathname;`,
      `(globalThis as any).OPENCODE_WORKER_PATH = new URL("./worker-entry.ts", import.meta.url).href;`,
      `(globalThis as any).OPENCODE_CHANNEL = '${Script.channel}';`,
      `(globalThis as any).OPENCODE_LIBC = ${item.os === "linux" ? "'glibc'" : "''"};`,
      `await import("./main.js");`,
    ].join("\n"),
  )

  // Write minimal deno.json for unstable flags
  await Deno.writeTextFile(
    path.join(bundleDir, "deno.json"),
    JSON.stringify({ unstable: ["bare-node-builtins", "sloppy-imports"] }, null, 2),
  )

  // Copy WASM files to bundle dir
  for (const wasmFile of [...new Set(wasmFiles)]) {
    const dest = path.join(bundleDir, path.basename(wasmFile, ".wasm") + ".bin")
    fs.copyFileSync(wasmFile, dest)
    console.log(`  copied ${path.basename(wasmFile)} -> ${path.basename(dest)}`)
  }
  const wasmIncludes = [...new Set(wasmFiles)].flatMap(f =>
    ["--include", path.join(bundleDir, path.basename(f, ".wasm") + ".bin")]
  )

  const includeArgs = [
    "--include", path.join(bundleDir, "worker.js"),
    "--include", path.join(bundleDir, "worker-entry.ts"),
    "--include", path.join(bundleDir, "parser.worker.js"),
    ...wasmIncludes,
	];
  await $`deno compile -A --no-check --target ${target} ${includeArgs} --output ${outBin} ${entryShim}`.cwd(bundleDir)

  await Deno.writeTextFile(
    `dist/${name}/package.json`,
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version

  await $`rm -rf ${bundleDir}`
}

await esbuild.stop()

await $`rm -rf ${path.join(dir, "dist/.bundle")}`

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber`
}

export { binaries }
